talenta_region/urls.py
from django.conf.urls import url
from talenta_region import views

app_name = 'talenta_region'

urlpatterns = [
    #url(r'^list_student/', views.list_student, name='list_student'),
    url(r'^add_municipio/', views.MunicipioCreate.as_view(), name='add_municipio'),
    url(r'^add_region/', views.RegionCreate.as_view(), name='add_region'),
    url(r'^edit_municipio/(?P<pk>\d+)/$', views.MunicipioEdit.as_view(), name='edit_municipio'),
    url(r'^edit_region/(?P<pk>\d+)/$', views.RegionEdit.as_view(), name='edit_region'),
    url(r'^delete_municipio/(?P<pk>\d+)/$', views.MunicipioDelete.as_view(), name='delete_municipio'),
    url(r'^delete_region/(?P<pk>\d+)/$', views.RegionDelete.as_view(), name='delete_region'),
    url(r'^list_municipios/', views.ListMunicipio.as_view(), name='list_municipio'),
    url(r'^list_regiones/', views.ListRegion.as_view(), name='list_regiones'),
    #url(r'^subject-data/$', subject_data_list, name='subject-data-list'),
    #url(r'^subject-data/(?P<pk>[0-9]+)/$', subject_data_detail, name='subject-data-detail')

]

talentatest/urls.py
from django.contrib import admin
from django.urls import path, include
from talenta_region import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'talenta_region/', include(urls)),
]

talenta_region/models.py
from django.db import models

# Create your models here.


class Municipio(models.Model):
    code = models.IntegerField(unique=True)
    name = models.CharField(max_length=150)
    STATUS = (
        ('Activo', 'Activo'),
        ('Inactivo', 'Inactivo')
    )
    status = models.CharField(max_length=20, choices=STATUS)

    def __str__(self):
        return u'{} {}'.format(self.name, self.code)


class Region(models.Model):
    code = models.IntegerField()
    name = models.CharField(max_length=150)
    municipios = models.ManyToManyField(Municipio)

    def __str__(self):
        return u'{} {}'.format(self.name, self.code)

talenta_region/forms.py
from django import forms
from talenta_region.models import Municipio, Region


class MunicipioForm(forms.ModelForm):
    class Meta:
        model = Municipio
        fields = '__all__'



class RegionForm(forms.ModelForm):
    class Meta:
        model = Region
        fields = '__all__'

        widgets = {
            'code': forms.TextInput(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'municipios': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

talenta_region/views.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.urls import reverse_lazy




# Create your views here.
from talenta_region.forms import MunicipioForm, RegionForm
from talenta_region.models import Municipio, Region


class ListMunicipio(ListView):
    template_name = 'list_municipio.html'
    model = Municipio


class ListRegion(ListView):
    template_name = 'list_region.html'
    model = Region


class MunicipioCreate(CreateView):
    model = Municipio
    form_class = MunicipioForm
    template_name = 'add_municipio.html'

    def get_success_url(self):
        return reverse_lazy('talenta_region:list_municipios')


class RegionCreate(CreateView):
    model = Region
    form_class = RegionForm
    template_name = 'add_region.html'

    def get_success_url(self):
        return reverse_lazy('talenta_region:list_regiones')


class MunicipioEdit(UpdateView):
    model = Municipio
    form_class = MunicipioForm
    template_name = 'edit_municipio.html'

    def get_success_url(self):
        return reverse_lazy('talenta_region:list_municipios')


class RegionEdit(UpdateView):
    model = Region
    form_class = RegionForm
    template_name = 'edit_region.html'

    def get_success_url(self):
        return reverse_lazy('talenta_region:list_regiones')


class MunicipioDelete(DeleteView):
    model = Municipio
    form_class = MunicipioForm
    template_name = 'delete_municipio.html'

    def get_context_data(self, **kwargs):
        context_data = super(MunicipioDelete, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        municipio = Municipio.objects.get(id=int(pk))
        context_data.update({'student': municipio})
        return context_data

    def get_success_url(self):
        return reverse_lazy('talenta_region:list_municipios')


class RegionDelete(DeleteView):
    model = Region
    form_class = RegionForm
    template_name = 'delete_region.html'

    def get_context_data(self, **kwargs):
        context_data = super(RegionDelete, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        region = Region.objects.get(id=int(pk))
        context_data.update({'student': region})
        return context_data

    def get_success_url(self):
        return reverse_lazy('talenta_region:list_regiones')

talenta_region/templates/add_municipio.html
{% extends "index.html" %}
{% load staticfiles %}

{% block main %}

    <br>

    <form method="post" class="form-horizontal">
        {% csrf_token %}

        {% for hidden in form.hidden_fields %}

            {{ hidden }}

        {% endfor %}

        <div class="form-group">
            <label for="{{ form.code.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.code.label }}</label>
            <div class="col-sm-8">
                {{ form.code }}
            </div>
        </div>
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.name.label }}</label>
            <div class="col-sm-8">
                {{ form.name }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.status.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.status.label }}</label>
            <div class="col-sm-8">
                {{ form.status }}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-8">
                <input class="btn btn-primary pull-right" type="submit" name="submit"
                       value="Save">
            </div>
        </div>


    </form>

{% endblock %}

talenta_region/templates/add_region.html
{% extends "index.html" %}
{% load staticfiles %}

{% block main %}

    <br>

    <form method="post" class="form-horizontal">
        {% csrf_token %}

        {% for hidden in form.hidden_fields %}

            {{ hidden }}

        {% endfor %}

        <div class="form-group">
            <label for="{{ form.code.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.code.label }}</label>
            <div class="col-sm-8">
                {{ form.code }}
            </div>
        </div>
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.name.label }}</label>
            <div class="col-sm-8">
                {{ form.name }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.municipios.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.municipios.label }}</label>
            <div class="col-sm-8">
                {{ form.municipios }}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-8">
                <input class="btn btn-primary pull-right" type="submit" name="submit"
                       value="Save">
            </div>
        </div>


    </form>

{% endblock %}

talenta_region/templates/delete_municipio.html
{% extends "index.html" %}
{% load staticfiles %}

{% block main %}

    <br>

    <form method="post" class="form-horizontal">
        {% csrf_token %}

        <p class="-align-center text-danger">Seguro que desea Eliminar al municipio {{ municipio.name }}?</p>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-8">
                <input class="btn btn-danger pull-right" type="submit" name="submit"
                       value="Delete">
            </div>
        </div>


    </form>

{% endblock %}

talenta_region/templates/delete_region.html
{% extends "index.html" %}
{% load staticfiles %}

{% block main %}

    <br>

    <form method="post" class="form-horizontal">
        {% csrf_token %}

        <p class="-align-center text-danger">Seguro que desea Eliminar la region {{ region.name }}?</p>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-8">
                <input class="btn btn-danger pull-right" type="submit" name="submit"
                       value="Delete">
            </div>
        </div>


    </form>

{% endblock %}

talenta_region/templates/edit_municipio.html
{% extends "index.html" %}
{% load staticfiles %}

{% block main %}

    <br>

    <form method="post" class="form-horizontal">
        {% csrf_token %}

        {% for hidden in form.hidden_fields %}

            {{ hidden }}

        {% endfor %}

        <div class="form-group">
            <label for="{{ form.code.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.code.label }}</label>
            <div class="col-sm-8">
                {{ form.code }}
            </div>
        </div>
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.name.label }}</label>
            <div class="col-sm-8">
                {{ form.name }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.status.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.status.label }}</label>
            <div class="col-sm-8">
                {{ form.status }}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-8">
                <input class="btn btn-primary pull-right" type="submit" name="submit"
                       value="Save">
            </div>
        </div>


    </form>

{% endblock %}

talenta_region/templates/edit_region.html
{% extends "index.html" %}
{% load staticfiles %}

{% block main %}

    <br>

    <form method="post" class="form-horizontal">
        {% csrf_token %}

        {% for hidden in form.hidden_fields %}

            {{ hidden }}

        {% endfor %}

        <div class="form-group">
            <label for="{{ form.code.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.code.label }}</label>
            <div class="col-sm-8">
                {{ form.code }}
            </div>
        </div>
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.name.label }}</label>
            <div class="col-sm-8">
                {{ form.name }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.municipios.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.municipios.label }}</label>
            <div class="col-sm-8">
                {{ form.municipios }}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-8">
                <input class="btn btn-primary pull-right" type="submit" name="submit"
                       value="Save">
            </div>
        </div>


    </form>

{% endblock %}

talenta_region/templates/home.html
{% extends "index.html" %}
{% load staticfiles %}

{% block main %}

    <h1>{{ request.user }}</h1>
    <h1>{{ request.user.get_full_name }}</h1>
    <a href="/logout">logout</a>

{% endblock %}

talenta_region/templates/index.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Freelancer - Start Bootstrap Theme</title>

    {% block css %}

        <!-- Bootstrap Core CSS -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Theme CSS -->
        <link href="{% static 'css/freelancer.min.css' %}" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
              type="text/css">

    {% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

<!-- Navigation -->
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li class="page-scroll">
                    <a href="#portfolio">Portfolio</a>
                </li>
                <li class="page-scroll">
                    <a href="#about">About</a>
                </li>
                <li class="page-scroll">
                    <a href="#contact">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>



<!-- Header -->
<header>


    <div class="container">
        <div class="row">
            {% block main2 %}

{% endblock %}
            <div class="col-lg-12">
                <img class="img-responsive" src="{% static 'img/profile.png' %}" alt="">
                <div class="intro-text">
                    <span class="name">Start Bootstrap</span>
                    <hr class="star-light">
                    <span class="skills">Web Developer - Graphic Artist - User Experience Designer</span>
                </div>
            </div>
        </div>
    </div>
</header>

{% block main %}

{% endblock %}

<!-- Contact Section -->
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Contact Me</h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Name</label>
                            <input type="text" class="form-control" placeholder="Name" id="name" required
                                   data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Email Address</label>
                            <input type="email" class="form-control" placeholder="Email Address" id="email" required
                                   data-validation-required-message="Please enter your email address.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Phone Number</label>
                            <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required
                                   data-validation-required-message="Please enter your phone number.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Message</label>
                            <textarea rows="5" class="form-control" placeholder="Message" id="message" required
                                      data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-success btn-lg">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

<!-- Footer -->
<footer class="text-center">
    <div class="footer-above">
        <div class="container">
            <div class="row">
                <div class="footer-col col-md-4">
                    <h3>Location</h3>
                    <p>3481 Melrose Place
                        <br>Beverly Hills, CA 90210</p>
                </div>
                <div class="footer-col col-md-4">
                    <h3>Around the Web</h3>
                    <ul class="list-inline">
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-dribbble"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="footer-col col-md-4">
                    <h3>About Freelancer</h3>
                    <p>Freelance is a free to use, open source Bootstrap theme created by <a
                            href="http://startbootstrap.com">Start Bootstrap</a>.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-below">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; Your Website 2016
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<div class="scroll-top page-scroll hidden-sm hidden-xs hidden-lg hidden-md">
    <a class="btn btn-primary" href="#page-top">
        <i class="fa fa-chevron-up"></i>
    </a>
</div>

{% block js %}

    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/freelancer.min.js' %}"></script>

{% endblock %}

</body>

</html>

talenta_region/templates/list_municipio.html
{% extends "index.html" %}
{% load staticfiles i18n %}

{% block main %}

    <div class="row ">

        <div class="col-md-6">
            <h1>Municipios</h1>
            <a class="btn btn-primary consultar" href="/logout">logout</a>

        </div>

    </div>

    <br>

    <div id="content-div" class="row col-md-8">
        <a id="search-subjects" class="btn btn-primary">Search</a>
        <div class="col-md-4">
            <input id="name-student" type="text" class="form-control">
        </div>

    </div>

    <br>

    <table class="table table-striped">
        <thead>
        <th>{% trans 'Código' %}</th>
        <th>{% trans 'Nombre' %}</th>
        <th>{% trans 'Estado' %}</th>
        <th>{% trans 'Editar' %}</th>
        <th>{% trans 'Eliminar' %}</th>

        </thead>

        <tbody id="subjects">

        {% for municipio in object_list %}
            <tr>
                <td>{{ municipio.code }}</td>
                <td>{{ municipio.name }}</td>
                <td>{{ municipio.status }}</td>
                <td><a class="btn btn-info" href="{% url 'talenta_region:edit_municipio' municipio.id %} ">Editar</a></td>
                <td><a class="btn btn-danger" href="{% url 'talenta_region:delete_municipio' municipio.id %} ">Eliminar</a></td>
            </tr>
        {% endfor %}


        </tbody>


    </table>



{% endblock %}


{% block js %}
    {{ block.super }}


{% endblock %}

talenta_region/templates/list_region.html
{% extends "index.html" %}
{% load staticfiles i18n %}

{% block main %}

    <div class="row ">

        <div class="col-md-6">
            <h1>Municipios</h1>
            <a class="btn btn-primary consultar" href="/logout">logout</a>

        </div>

    </div>

    <br>

    <div id="content-div" class="row col-md-8">
        <a id="search-subjects" class="btn btn-primary">Search</a>
        <div class="col-md-4">
            <input id="name-student" type="text" class="form-control">
        </div>

    </div>

    <br>

    <table class="table table-striped">
        <thead>
        <th>{% trans 'Código' %}</th>
        <th>{% trans 'Nombre' %}</th>
        <th>Editar</th>
        <th>Eliminar</th>

        </thead>

        <tbody id="subjects">

        {% for region in object_list %}
            <tr>
                <td>{{ region.code }}</td>
                <td>{{ region.name }}</td>
                <td><a class="btn btn-info" href="{% url 'talenta_region:edit_region' region.id %} ">Editar</a>
                </td>
                <td><a class="btn btn-danger"
                       href="{% url 'talenta_region:delete_region' region.id %} ">Eliminar</a></td>

            </tr>
        {% endfor %}


        </tbody>


    </table>



{% endblock %}


{% block js %}
    {{ block.super }}


{% endblock %}

talenta_region/templates/list_student.html
{% extends "index.html" %}
{% load staticfiles %}

{% block main %}

    <br>
    <a class="btn btn-primary" href="{% url 'course:create_student' %}">Nuevo Estudiante</a>
    <br>

    <form>

    </form>

    <p align="center" class="text-success fa-2x">Lista de Estudiantes</p>

    <div>

        <table class="table table-bordered">
            <thead>

            <th>Nombre</th>
            <th>Apellido</th>
            <th>Editar</th>
            <th>Delete</th>

            </thead>

            <tbody>
            {% for stu in student %}
                <tr>
                    <td>{{ stu.name }}</td>
                    <td>{{ stu.last_name }}</td>
                    <td><a class="btn btn-info" href="{% url 'course:edit_student' stu.id %} ">Editar</a></td>
                    <td><a class="btn btn-danger" href="{% url 'course:delete_student' stu.id %} ">Eliminar</a></td>

                </tr>



            {% endfor %}

            </tbody>


        </table>


    </div>

{% endblock %}